# application.yml
# YML文件格式是YAML (YAML Aint Markup Language)编写的文件格式,YAML是一种直观的能够被电脑识别的的数据数据序列化格式,他并且容易被人类阅读.
# 注意：yml的缩进，使用空格符，而不要使用tab键

# 应用信息
application:
  title: elven-paln
  version: 1.0-SNAPSHOT
  formatted-version: (1.0)
info:
  contact:
    email: elve1984@163.com
    phone-no: 18888888888

# 服务信息
server:
  servlet:
    context-path: /elven-plan
  port: 8888

# spring.application
spring:
  application:
    name: elven-plan
    admin:
      enabled: false
  main:
    banner-mode: "console" # off, log
  banner:
    location: banners/elven-plan-banner.txt

