# application.yml
# YML文件格式是YAML (YAML Aint Markup Language)编写的文件格式,YAML是一种直观的能够被电脑识别的的数据数据序列化格式,他并且容易被人类阅读.
# 注意：yml的缩进，使用空格符，而不要使用tab键

# 应用信息
application:
  name: elven-plan
  version: 1.0-SNAPSHOT
  formatted-version: (1.0)
info:
  contact:
    email: elve1984@163.com
    phone-no: 18888888888

# 日志配置
logging:
  config: classpath:logging/logback-spring.xml
  level:
    root: INFO #FATAL ERROR WARN INFO DEBUG TRACE
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    elven-plan: DEBUG
  group.elven-plan: site.elven.plan.plugin, site.elven.plan.web
  file:
    path: ./logs
    name: ./logs/${application.name}.log
    max-history: 1
    max-size: 10MB


# 开启debug和trace模式，同时打开了日志debug和trace级别
debug: false
trace: false

# 服务信息
server:
  servlet:
    context-path: /elven-plan
  port: 8888

# spring.application
spring:
  application:
    name: elven-plan
    admin:
      enabled: false
  main:
    banner-mode: "console" # off, log
  banner:
    location: banners/elven-plan-banner.txt

acme:
  remote-address: 192.168.1.1
  security:
    username: admin
    roles:
      - USER
      - ADMIN